#version 450
#extension GL_GOOGLE_include_directive : require

#include "../../src/Engine/src/graphics/gpu_types.hpp"


layout (local_size_x = INDIRECT_SET_LOCAL_SIZE_X) in;
layout (push_constant) uniform PushConstants
{
	int instanceCount;
} constants;

layout(std430, set = INDIRECT_SET_ID, binding = INDIRECT_SET_BIND_ID_INSTANCE_COUNTER) buffer InstanceCounters
{
	uint instanceCounter[];
};

layout(std430, set = INDIRECT_SET_ID, binding = INDIRECT_SET_BIND_ID_INSTANCE_INFO) readonly buffer InstanceInfos
{
	// InstanceInfo lives inside gpu_types.hpp
	InstanceInfo instances[];
};

bool is_inside_frustum(vec3 c, float r)
{
	// TODO: Culling math goes here
	return true;
}

void main()
{
	uint id = gl_GlobalInvocationID.x;
	if (id >= constants.instanceCount)
	{
		return;
	}

	int meshID = instances[id].meshID;
	if (is_inside_frustum(vec3(0), 0.0))
	{
		atomicAdd(instanceCounter[meshID], 1u);
	}
}