#version 450
#extension GL_GOOGLE_include_directive : require

#include "../../src/Engine/src/graphics/gpu_types.hpp"


layout (local_size_x = INDIRECT_SET_LOCAL_SIZE_X) in;
layout (push_constant) uniform PushConstants
{
	int totalInstances;
} constants;

layout(std430, set = INDIRECT_SET_ID, binding = INDIRECT_SET_BIND_ID_INSTANCE_COUNTER) writeonly buffer InstanceCounters
{
	uint instanceCount[];
};

layout(std430, set = INDIRECT_SET_ID, binding = INDIRECT_SET_BIND_ID_INSTANCE_INFO) readonly buffer InstanceInfos
{
	// InstanceInfo lives inside gpu_types.hpp
	InstanceInfo instances[];
};

bool is_inside_frustum(vec3 c, float r)
{
	// TODO: Culling math goes here
	return true;
}

void main()
{
	uint id = gl_GlobalInvocationID.x;
	if (id >= constants.totalInstances)
	{
		return;
	}

	int meshID = instances[id].meshID;
	if (is_inside_frustum(vec3(0), 0.0))
	{
		atomicAdd(instanceCount[meshID], 1u);
	}
}



//void main()
//{
//	uint gID = gl_GlobalInvocationID.x;
//	bModelMatrices.matrix[gID] = mat4(vec4(2.0), vec4(4.0), vec4(6.0), vec4(8.0));
//
//	if(gID == 0)
//	{
//		bDrawParamBuffer.arr[gID].indexCount = 54972;
//		bDrawParamBuffer.arr[gID].instanceCount = 1;
//		bDrawParamBuffer.arr[gID].firstIndex = 0;
//		bDrawParamBuffer.arr[gID].vertexOffset = 0;
//		bDrawParamBuffer.arr[gID].firstInstance = 0;
//
//
//		bModelMatrices.matrix[gID] = mat4(1.0);
//
//		bDrawCountBuffer.arr[0].count += 1;
//	}
//	if(gID == -2)
//	{
//		bDrawParamBuffer.arr[gID].indexCount = 36;
//		bDrawParamBuffer.arr[gID].instanceCount = 1;
//		bDrawParamBuffer.arr[gID].firstIndex = 0;
//		bDrawParamBuffer.arr[gID].vertexOffset = 0;
//		bDrawParamBuffer.arr[gID].firstInstance = 0;
//
//
//		bModelMatrices.matrix[gID] = mat4(1.0);
//		bDrawCountBuffer.arr[0].count += 1;
//	}
//}