function(update_output_directory PROJECT)
    set_target_properties(${PROJECT} PROPERTIES RUNTIME_OUTPUT_DIRECTORY "${OUTPUT_DIRECTORY}")
    set_target_properties(${PROJECT} PROPERTIES RUNTIME_OUTPUT_DIRECTORY_DEBUG "${OUTPUT_DIRECTORY}")
    set_target_properties(${PROJECT} PROPERTIES RUNTIME_OUTPUT_DIRECTORY_RELEASE "${OUTPUT_DIRECTORY}")
    set_target_properties(${PROJECT} PROPERTIES OUTPUT_NAME_DEBUG "${PROJECT}d")
    set_target_properties(${PROJECT} PROPERTIES OUTPUT_NAME_RELEASE "${PROJECT}")
endfunction()

function(enforce_cxx_standard PROJECT)
    set_target_properties(${PROJECT} PROPERTIES CXX_STANDARD 23)
    set_target_properties(${PROJECT} PROPERTIES CXX_STANDARD_REQUIRED ON)
endfunction()
